# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O9d4QYTkqfYSjFFbeZOO0zTe-_V-Vwnc
"""

pip install streamlit opencv-python numpy

import streamlit as st
import cv2
import numpy as np

st.title("🖼️ Smart Image Processing Toolkit")

# Upload image
uploaded_file = st.file_uploader("Upload an image", type=["jpg", "png", "jpeg"])

if uploaded_file is not None:
    # Convert file to OpenCV image
    file_bytes = np.asarray(bytearray(uploaded_file.read()), dtype=np.uint8)
    image = cv2.imdecode(file_bytes, 1)

    st.image(image, caption="Original Image", use_column_width=True)

    st.sidebar.title("Choose Operation")

    option = st.sidebar.selectbox(
        "Select Feature",
        ("None", "Grayscale", "Blur", "Edge Detection", "Histogram Equalization", "Flip Image")
    )

    # Grayscale
    if option == "Grayscale":
        gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
        st.image(gray, caption="Grayscale Image")

    # Blur
    elif option == "Blur":
        blur = cv2.GaussianBlur(image, (5,5), 0)
        st.image(blur, caption="Blurred Image")

    # Edge Detection
    elif option == "Edge Detection":
        edges = cv2.Canny(image, 100, 200)
        st.image(edges, caption="Edge Detection")

    # Histogram Equalization
    elif option == "Histogram Equalization":
        gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
        equalized = cv2.equalizeHist(gray)
        st.image(equalized, caption="Histogram Equalized")

    # Flip
    elif option == "Flip Image":
        flipped = cv2.flip(image, 1)
        st.image(flipped, caption="Flipped Image")